# Generated by Django 6.0.2 on 2026-02-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tform',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
