# Generated by Django 6.0.3 on 2026-04-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patient_orientation_and_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
