# Generated by Django 6.0.3 on 2026-04-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emergencyloginattempt_passwordresettoken_patient_and_more'),
        ('api', '0005_delete_complaint'),
    ]

    operations = [
    ]
