# Generated by Django 6.0.3 on 2026-04-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contactrequest'),
        ('api', '0008_segmentationrun_segmentationmaskresult'),
    ]

    operations = [
    ]
