# Generated by Django 6.0.3 on 2026-04-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20260409_1500'),
        ('api', '0012_testimonial'),
    ]

    operations = [
    ]
