# Generated by Django 6.0.3 on 2026-04-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_mrifile_add_file_type'),
        ('api', '0017_remove_segmentationmaskresult_restore_model1_unlocked'),
    ]

    operations = [
    ]
