# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_merge_20260425_1924"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="emergency_temp",
            field=models.BooleanField(
                default=False,
                db_index=True,
                help_text="Dossier jetable créé en session urgence (exclu des listes médecin).",
            ),
        ),
    ]
