# Generated by Django 6.0.3 on 2026-05-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_patient_emergency_temp'),
        ('api', '0019_patient_report'),
    ]

    operations = [
    ]
