# Generated by Django 6.0.3 on 2026-05-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_reference_intensity_and_analyse'),
        ('api', '0021_segmentationrun_volumes'),
    ]

    operations = [
    ]
